spring:
  cloud:
    gateway:
      routes:
        - id: aliyun-asr-demo-realtime-websocket
          uri: ws://127.0.0.1:8080
          predicates:
            - Path=/aliyun-asr-demo/realtime
        - id: aliyun-asr-demo-http
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/aliyun-asr-demo/**
